name: Publish Docker image

on: push 
jobs:
  docker_registery:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
# extract the latest version of the code 
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: run tests _test.go
        run: go build -v ./...
        run: go test ./...*_tests.go
        
