name: Notify resources-types in change 
on: push

jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: Invoke workflow in another repo with inputs
         uses: benc-uk/workflow-dispatch@v1
         with:
            workflow: CI_CD pipeline
            repo: monikamikhaiel/resource-types/
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
