name: CI_CD pipeline 

on: push 
jobs:
  Build_test:
    name: build and test go app 
    runs-on: ubuntu-latest
    steps:
# extract the latest version of the code 
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
           submodules: true
      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
           repository: monikamikhaiel/resource-types
# install go binaries and setup the environment 
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: build and run test 
        working-directory: ./warehouse
        run: |
              go build -v
              go test 
        
