name: CI_CD pipeline 

on: push 
jobs:
  Build_test:
    name: build and test go app 
    runs-on: ubuntu-latest
    steps:
# extract the latest version of the code 
      - name: Check out the repo
        uses: actions/checkout@v2
# install go binaries and setup the environment 
      - name: Setup go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: chcekout the 2nd repo of resources types 
        run:  git submodule update --remote
      - name: build and run test 
        working-directory: ./warehouse
        run: |
              go build -v
              go test 
        
